### ISSUE TITLE
saved_prefs.ini

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#1]
Two issues I noticed:
 1) The saved_prefs.ini file doesn't work when it's in the same folder as the psydoom.exe like the other ini files do.
 2) There should probably be a separate "lastPassword=" for each cue file that is loaded. (Example: If I load up Doom.cue and beat map01, that password currently carries over to when I load up FinalDoom.cue.)

**Comment by dcoy-glu** [comment]
Hey @fenderc01 thanks for pointing out those issues! On (1) I agree it's somewhat inconsistent currently - I can fix. For (2) though it is a corner case we could have a separate password field for each game type - Doom vs Final Doom, and possibly GEC Master Levels in future.

**Comment by BodbDearg** [comment]
Issue (1) is now addressed by 5a41f9e63f96897ce0163b4e5964f8e9e44979fa

**Comment by BodbDearg** [comment]
Issue (2) is addressed by a8514f548e6160dc70bba3a882da42bf59e60204.

**Comment by fenderc01** [comment]
> For (2) though it is a corner case we could have a separate password field for each game type - Doom vs Final Doom, and possibly GEC Master Levels in future.

Could you add in lastPassword_GecMe to the saved_prefs.ini file?

**Comment by BodbDearg** [comment]
Good call, this should be added in - thanks!

**Comment by BodbDearg** [comment]
A separate GEC ME last password has now been added as of 1.0.0 - closing ticket again.
