### ISSUE TITLE
GEC Master Edition Beta 4 - level order

### ISSUE THREAD

**Issue by palmerj** [BodbDearg/PsyDoom#103]
I can get GEC Master Edition Beta 4 to load, but levels loaded do not match the selection in the main menu. Is there some fix for this?

**Comment by palmerj** [comment]
Any idea?

**Comment by bangstk** [comment]
This isn't a bug. GEC Master Beta 4 contains ONLY levels that are NOT in the original PSX Doom releases. Therefore, each episode can only start on the levels contained in GEC Master Beta 4,

**Comment by palmerj** [comment]
AH right - thank you. Is there something that rolls all of this together?
