### ISSUE TITLE
Saturn Doom support?

### ISSUE THREAD

**Issue by DrAzathoth** [BodbDearg/PsyDoom#108]
Under the hood, the Saturn port of Doom is very similar to the PlayStation port. Using that logic, would it be feasible to have limited support for running Saturn Doom’s assets?

**Comment by BodbDearg** [comment]
Thanks for the suggestion. I investigated but unfortunately it seems like a lot more trouble than its worth. Perhaps some brave soul will look at a proper Saturn port some day...

**Comment by DrAzathoth** [comment]
@BodbDearg, could you provide some of the research/documentation you gathered in your investigation? Even if there isn’t much, it could be valuable to anyone looking to tackle this.

**Comment by BodbDearg** [comment]
There isn't anything new to share really, I'm afraid. I just gauged how much effort it would involve and what the benefit would be.
