### ISSUE TITLE
Mouselook

### ISSUE THREAD

**Issue by coldner** [BodbDearg/PsyDoom#109]
It would be really nice to temporarily look up and down, especially in high rooms.

**Comment by BodbDearg** [comment]
Gave it some more consideration, but still against this feature for a couple of reasons:
- It disrupts the look and feel of the game and makes it less like Doom.
- Sprites can look poor (like cardboard cutouts) when looking up and down and this breaks immersion. They were never intended to be viewed that way.
- The feature can introduce potential sequence breaking and other issues for maps designed without this feature in mind.
- It can cause visual issues with things like skies.
- It would only be feasible to do (properly) for the Vulkan renderer, and would therefore introduce inconsistency between the classic and Vulkan renderers. Note: technically you could do a skew transform like how Duke3D implemented 'looking up and down' but that doesn't look great IMHO.
