### ISSUE TITLE
Full map props interpolation and ROM unpacking

### ISSUE THREAD

**Issue by Patrxgt** [BodbDearg/PsyDoom#11]
Hello, firstly, I want to thank you for making this project, so now I can play PSX Doom with mouse, keyboard, bugfixes, 60fps and modern resolutions support.

Secondly, I have two questions:
1. Is there an option to add interpolation to the props on the map (eg doors and elevators)? Asking, because it's kinda annoying, when everything feels so smooth, but when you open the doors this feeling falls apart because of choppy animation of those.
2. Can you add possibility to unpack ROMs of Doom and Final Doom to make modding easier? It would be very cool to have actual game files in the folder than bunch of .bin files and one .cue file.

**Comment by BodbDearg** [comment]
Hi @Patrxgt thanks for your interest in the project, glad to hear you are enjoying. Regarding your questions:

(1) There is no option for this currently but the feature will be implemented in future versions of PsyDoom, likely version 0.9. I will close the ticket once implemented.
(2) There are already many tools out there that can do this sort of thing for you so I wouldn't consider it necessary to add this functionality to PsyDoom. An example which I use is 'jpsxdec': https://github.com/m35/jpsxdec

**Comment by BodbDearg** [comment]
Interpolation of map objects, sectors and the player weapon is now implemented as of 1.0.0.
