### ISSUE TITLE
portable use?

### ISSUE THREAD

**Issue by PittStone** [BodbDearg/PsyDoom#111]
I see that PsyDoom Data directory is not the same Folder. Its in "AppData\Roaming" folder. I hate this. Because i like to use One PsyDoom for "DOOM" and one for "FinalDoom". But i can only use one Game Disc. 
I like to use start Psydoom with a Game Disc via Batch file. Is this Possible?

**Comment by BodbDearg** [comment]
Yes this is possible. You can specify the game disc to use via a command line argument:
> The .cue file used can be manually specified on launch via `-cue <CUE_FILE_PATH>.`

See: https://github.com/BodbDearg/PsyDoom?tab=readme-ov-file#Command-line-arguments
