### ISSUE TITLE
[Feature] PC DOOM-based enhanced Software rendering

### ISSUE THREAD

**Issue by lafoxxx92** [BodbDearg/PsyDoom#119]
Add renderer based on Software Rendering as seen in the Vanilla DOOM or similar projects (like Chocolate DOOM), but with extra features (like 16 bit color, translucency and colored lighting).
This should make the game less demanding and no longer rely on GPU emulation which consumes plenty of CPU cycles.

**Comment by BodbDearg** [comment]
Beyond the scope of this project - sorry. One of the core aims of PsyDoom is to emulate the look and feel of PSX Doom, not to add in PC-like software rendering. Lighting and shading is a big part of the PSX look and I don't want to deviate from what we have now. Also, it won't make as much of a performance difference as you might think if also adding in 16-bit color, transparency etc.
