### ISSUE TITLE
Coop desync issues with Text-based Intermissions

### ISSUE THREAD

**Issue by Ch0wW** [BodbDearg/PsyDoom#18]
During a coop-playthrough with a friend of the port, we have noticed our game constantly desynced on both Text-Intermissions on DOOMPSX, that are on maps 30 and 54.

As a result, either the link is cut (meaning we had to pistol start MAP31), or it led to desyncs on the cast monsters (MAP54).

We haven't tested on Final Doom yet, as we do not know yet if there are any text-intermissions in it.

EDIT: Although unsure if it's because of it or not, but be were both on Vulkan renderer.

**Comment by BodbDearg** [comment]
Thanks for reporting this issue! The coop game should end and the game should return to the main menu after the intermission or finale (same as single player) but there should not be a de-sync error. I will investigate.

**Comment by BodbDearg** [comment]
Hmmm not able to reproduce the end game de-sync issue in current versions of PsyDoom. I know I did make some changes around the end game behavior for co-op recently, perhaps that fixed it.
