### ISSUE TITLE
Very awkward keyboard delay (regardless of interpolation)

### ISSUE THREAD

**Issue by vananasun** [BodbDearg/PsyDoom#20]
Sometimes when I strafe around the map, I notice really bad input lag of what feels is about 200ms. Sometimes a key only registers when I released it.

Before you ask: The movement input tweak that puts the player movement logic after input processing is turnt on.

**Comment by vananasun** [comment]
Closed because I prooooooooobably have a keylogger :)

**Comment by BodbDearg** [comment]
Oh dear - hope you get that resolved! Thanks for updating the ticket. Yeah it wouldn't really make sense (in a normal environment) that input would just suddenly be ignored since the game polls it from the OS every frame. If part of the OS is malware however, that might be a different story...
