### ISSUE TITLE
Option for saving game/quicksaves

### ISSUE THREAD

**Issue by TheOldKingCole** [BodbDearg/PsyDoom#22]
I don't know how possible this is, though maybe it could work like save states on emulators.

**Comment by BodbDearg** [comment]
Thank you! Saves are planned to be implemented for a future release. Please note however for now the project is on pause, see: https://www.doomworld.com/forum/topic/111024-psydoom-083-psx-doom-port-reverse-engineered-for-pc/?page=23&tab=comments#comment-2411357

**Comment by BodbDearg** [comment]
Saves are now implemented as of 1.0.0.
