### ISSUE TITLE
External setup program

### ISSUE THREAD

**Issue by OpenRift412** [BodbDearg/PsyDoom#24]
PsyDoom has a LOT of settings under the hood, I think it would probably be a bit more user-friendly if there was an external program to set controls and other options, akin to how Chocolate Doom does it.

**Comment by OpenRift412** [comment]
Some graphics and compatibility presets would also be nice to have as well. For example, having an uncapped framerate only when playing in the Vulkan renderer.

**Comment by BodbDearg** [comment]
Thank you for the suggestion! Yes this is something that's been under consideration, will keep the issue here as a reminder.

**Comment by BodbDearg** [comment]
This is now implemented as of 1.0.0.
