### ISSUE TITLE
small weapons

### ISSUE THREAD

**Issue by tomatothesaddo** [BodbDearg/PsyDoom#28]
for some reason no matter what options i mess around with the weapons all look small and smushed, especially the super shotgun, which looks like doomguy is playing around with some toothpick
![PsyDoom 0 8 3 1_15_2022 7_43_28 PM](https://user-images.githubusercontent.com/83978807/149642856-c397dcd2-c6fd-4163-9bd8-aef3ce72aa34.png)
(using 0.8.3)

**Comment by OpenRift412** [comment]
I mean, that's just how it looks normally in PSX Doom, so it's accurate.

**Comment by BodbDearg** [comment]
@OpenRift412 is correct, this is how the game looks on the original hardware. They did scale down some of the original sprites for this port with the Super Shotgun seemingly suffering the most. They seemed to have corrected for this somewhat with Final Doom, and re-did the Super Shotgun - it looks much better in that edition of the game.

But yeah, this is just how the assets look for PSX Doom.
