### ISSUE TITLE
Pain Face for Both Players in Deathmatch

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#30]
While playing DM, I noticed when my opponent walks in acid, the face for my player would show pain. It doesn't seem to do it for any other damage that I was aware of.

**Comment by BodbDearg** [comment]
That's an odd one - nice find! Looks like it occurs in the original binary too, the code that applies the sector special doesn't check which player is getting hurt and updates the status bar even if it isn't you.

**Comment by BodbDearg** [comment]
This bug should be fixed as of 1.0.0 - closing ticket.
