### ISSUE TITLE
Co-Op: Kill Stats

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#32]
In co-op, kill stats are not shared between players. This is okay for the tally screen at the end of the level, but can be confusing for the stat display that can be shown during gameplay (KSI display).

Maybe it could show Player Kills/Total Kills/Total Enemies (Example: 10/30/50).

**Comment by BodbDearg** [comment]
Good callout! I think a joint count during gameplay (yours + the other player) and then a separate count on the tally screen makes the most sense. This way both players know when the level has been maxed out during gameplay and also get a breakdown of who got what at the end.

**Comment by BodbDearg** [comment]
The changes mentioned are now implemented as of 1.0.0.
