### ISSUE TITLE
Feature Request: Configurable Multiplayer Options

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#37]
I have a few suggestions for multiplayer. These could either be set from a menu that pops up before connecting, through a command line option, or by some other means. Obviously, bug fixes take higher priority, but I believe this would enhance the multiplayer experience.

- Deathmatch
    - Scoreboard Overlay
    - Time Limit
    - Frag Limit
    - Exit Enable/Disable

- Cooperative
    - Friendly Fire Enable/Disable

**Comment by BodbDearg** [comment]
Thanks for the suggestions! My thoughts added to #58 more or less sum up how I feel about multiplayer. TLDR it isn't really a focus of this port and would require too many changes to provide a decent experience. For these reasons I don't really want to invest much more time on MP I'm afraid, other than small bug fixes and such.
