### ISSUE TITLE
Widescreen fire in the title animation in Vk renderer?

### ISSUE THREAD

**Issue by OpenRift412** [BodbDearg/PsyDoom#39]
Would it be possible to have it so when the Vulkan renderer is enabled, the title animation displays the fire animation in widescreen? It would be a nice enhancement, I think.

**Comment by BodbDearg** [comment]
I had considered this previously but decided against it because the rest of the menu UI would not be able to support widescreen due to limitations of the artwork.

It's better to be consistent throughout the menus rather than have jarring transitions between widescreen and non widescreen modes.
