### ISSUE TITLE
GEC ME: Map Bugs

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#41]
I was going to try patching these myself, but I couldn't figure out how to get the MD5 hash of the map. This applies to the latest commit.

- MAP07 (Against Thee Wickedly), Sector 95 should have no effect instead of causing damage
- MAP32 (Trapped on Titan), Thing 370 is preventing the sector from lowering when the switch is flipped.

**Comment by BodbDearg** [comment]
Thanks for pointing these out @fenderc01! There's going to be a lot more patches for the GEC ME coming in future commits, these bugs will definitely be on the radar also.

**Comment by fenderc01** [comment]
Looks like you fixed this now. Closing...

**Comment by BodbDearg** [comment]
Awesome - thank you @fenderc01!
