### ISSUE TITLE
Co-Op: Spawned enemies (lost souls) don't count towards kill tally if they die upon spawning

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#45]
In co-op, if a lost soul dies immediately upon spawning from a pain elemental, it does not count towards the kill count. This happens when the lost soul runs into the player or a wall when spawning.

**Comment by BodbDearg** [comment]
Interesting corner case, thanks for raising!

**Comment by BodbDearg** [comment]
The changes mentioned have now been implemented as of 1.0.0.
