### ISSUE TITLE
Another computer area map cannot be picked up

### ISSUE THREAD

**Issue by getphobo** [BodbDearg/PsyDoom#49]
Playing the secret Fortress of Mystery map, I noticed that if there are multiple computer area maps and the player picks up one of them, another one cannot be picked up anymore and so will affect item count, making a 100% item score impossible.

**Comment by fenderc01** [comment]
@BodbDearg Would it be better to allow both computer maps to be picked up or remove the east-most computer map, since the PC version only has the computer map in the southwest corner of the first room?

**Comment by BodbDearg** [comment]
I think just allowing multiple pickups would be best, that way it won't be a problem on any other maps too.

**Comment by BodbDearg** [comment]
Picking up multiple maps is now implemented as of 1.0.0 - closing ticket.
