### ISSUE TITLE
Support for "Hacks" such as PlayStation Doom: Master Edition

### ISSUE THREAD

**Issue by joelcresswell** [BodbDearg/PsyDoom#5]
Hello and sorry if this is the wrong place for suggestions or queries. 

I've been enjoying PsyDoom and I wonder if you've considered support for PS1 hacks such as the Master Edition: https://doomwiki.org/wiki/PlayStation_Doom:_Master_Edition

Thanks for your hard work!~

**Comment by BodbDearg** [comment]
Hello @joelcresswell glad to hear you are enjoying the project! I'm planning to support the GEC ME once beta 4 comes out and I know what the structure of the game disc will look like. At the minute the project is sort of a moving target and a lot will change in the next release, so I'm waiting until then when things settle down. See my comments on Doomworld:

https://www.doomworld.com/forum/topic/111024-psydoom-060-psx-doom-port-reverse-engineered-for-pc/?do=findComment&comment=2227806

We can leave this ticket open as a reminder though, just in case I forget - thanks :)

**Comment by joelcresswell** [comment]
Thanks a lot! Looking forward to it 👍

**Comment by BodbDearg** [comment]
Support for the GEC ME Beta 3 has now been added as 1.0.0. Once Beta 4 is available I'll also add support for that too. That is a separate future task however - hence closing this ticket.
