### ISSUE TITLE
Question on the exact frame rate

### ISSUE THREAD

**Issue by getphobo** [BodbDearg/PsyDoom#50]
So, I was wondering: Does this game run at 29.97 fps or 30.00 fps?

**Comment by BodbDearg** [comment]
For NTSC mode the original PSX Doom _tries_ to do a player tick/update every two vertical blanks or refreshes of the screen. According to the No$PSX specs (http://problemkaputt.de/psx-spx.htm#gputimings) the refresh rate for the GPU is ~59.29 Hz which means that the game updates at 29.645 Hz (59.29/2 Hz). Note the emphasis on the word 'try' - the game often falls short of running at it's near 30 Hz target, more often than not it's hovering around 15 Hz or even lower...

PsyDoom on the other hand will tick the game at 30 Hz, which is a _tiny_ bit faster than the original game but unnoticeable in practice.
