### ISSUE TITLE
Bug: Specific Crash on MAP20 - Unholy Cathedral

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#53]
This is a very specific, edge-case bug. Not sure if it's worth your time or not, but here's how I can reproduce it.
1. Warp to MAP20 - Unholy Cathedral
2. Save the game
3. Load the save file you just created
4. Try to "open" linedef 499 or 501 (east door frame beside northeast teleport) and the game crashes

This problem with linedefs 499 and 501 (609 and 611 on PC Doom) is a [documented bug](https://doom.fandom.com/wiki/E3M5:_Unholy_Cathedral_(Doom)#Bugs) on this map. For some reason, it only crashes after loading a save file. As a side note, it also crashes when running the game in RetroArch (PCSX ReARMed).

I also noticed it does the same thing for linedefs 217 and 220 (242 and 245 on PC) in the west-most room (also documented in the link above.)

**Comment by fenderc01** [comment]
Obviously, this could be patched out of the map, but maybe it's worthwhile to fix the crash.

**Comment by BodbDearg** [comment]
Good callout, thanks! I think it's worthwhile fixing it both ways. The map patch will remove the strange, supposedly 'useable' lines. An engine-level fix to just ignore this mapping error would also make the game more robust for future maps.

Odd that it only crashed in PsyDoom _after_ you reloaded the save file. I think maybe the undefined behavior this bug triggered might have corrupted some of the game state which then got carried forward to the save, causing issues later.

**Comment by BodbDearg** [comment]
Should be fixed as of 1.0.0 - closing ticket.
