### ISSUE TITLE
Interpolation/FPS Cap Toggle Key?

### ISSUE THREAD

**Issue by OpenRift412** [BodbDearg/PsyDoom#54]
With the engine in the state it is right now (congrats on the 1.0 release by the way!), would it be possible to implement a sort of in-game toggle for interpolation or FPS cap? I think this would be a nice toggle to have alongside the renderer toggle, that way you can hotswap between say vulkan at uncapped FPS w/ interpolation and the software renderer with the original FPS cap and no interpolation. 

I'd imagine it would work by having the interpolation options decided in the launcher and then the toggle turning those pre-selected options on or off.

Would this be doable?

**Comment by BodbDearg** [comment]
This is now implemented in the 1.0.1 release - closing ticket.
