### ISSUE TITLE
Simpler Savegame Messages

### ISSUE THREAD

**Issue by OpenRift412** [BodbDearg/PsyDoom#55]
Just a little thing that would probably be good to help the game feel a little more clean, maybe instead of having it say "Saved to filename.sav" or "Loaded filename.sav", it could be something a bit more intuitive like "Saved to Slot (1-3)" and "Quicksaved" for saving and "Loaded Slot (1-3)", "Loaded Quicksave" and "Loaded from Autosave" for loading.

**Comment by BodbDearg** [comment]
Thanks for the suggestion, this will be implemented in 1.0.1 by 3e2eb7dfbb81a8d156cf4319afbc157a7fbd70b0. The ticket can be closed once that release is available.

**Comment by BodbDearg** [comment]
1.0.1 is now released, closing ticket.
