### ISSUE TITLE
[Bug] Fix for Final Doom STATUS lump

### ISSUE THREAD

**Issue by NightFright2k19** [BodbDearg/PsyDoom#61]
Final Doom's STATUS gfx lump has a glitch with two non-transparent pixels which cause the blue and yellow keycard on the statusbar to have purple pixels at their right/left edges.

[Issue on Doomworld](https://www.doomworld.com/forum/post/2556199)
[Sprite sheet](https://static.doomworld.com/monthly_2022_10/STATUS.png.fbed472079d37f8da6131b5bed127367.png)

I guess one solution would be to make a mod which fixes that lump, but maybe it could even be handled by your port directly. Something like: "If Final Doom is loaded, make pixels at sprite coords x1/y1 and x2/y1 on the STATUS lump transparent".

**Comment by BodbDearg** [comment]
Closing as fixed as of 1.1.0.
