### ISSUE TITLE
[Suggestion] Interpunctuation for Quicksave/Quickload

### ISSUE THREAD

**Issue by NightFright2k19** [BodbDearg/PsyDoom#62]
To be on par with the rest of the game messages which are written as full sentences (e.g. "Picked up a clip."), it would look nicer if the quicksave/quickload messages had full stops at their end as well, i.e. "Quicksaved." and "Quickloaded.".

**Comment by BodbDearg** [comment]
Closing as implemented as of 1.1.0.
