### ISSUE TITLE
[Feature] Color-coded things on automap

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#65]
I don't know how the IDDT cheat code works in the original DOS or Playstation game, but in Crispy Doom, the things shown on the map are color-coded. In particular, enemies are red, and items that count toward the player's "items" total are yellow.
![image](https://user-images.githubusercontent.com/114965480/197311236-b80f3e8d-0a30-41eb-8e5f-0766b4104719.png)
By contrast, PsyDoom's IDMT cheat code shows all things in uniform blue.
![image](https://user-images.githubusercontent.com/114965480/197316384-29346ade-d75a-4699-8d91-10d6fd6239fe.png)
Adding color-coding would make going for 100% scores a lot less frustrating.

Edit: Color coding for secret lines/sectors, as seen with the fuchsia outlines in the Crispy Doom screenshot, would be nice too.

**Comment by BodbDearg** [comment]
Closing as implemented as of 1.1.0.
