### ISSUE TITLE
[Feature] Difficulty indicator

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#67]
It would be convenient to have some way to check either which difficulty setting is currently in effect in a game, or what setting a save file is using.

**Comment by BodbDearg** [comment]
Thanks for the suggestion! Had a think about it and unfortunately there isn't really a great place to put this info without cluttering up the UI. The benefits of this seem pretty minimal in most cases so I don't think it's worth trying to force it in. A lot of Doom source ports seem to take a similar approach too - even GZDoom doesn't show difficulty within its save menu.
