### ISSUE TITLE
[Feature] Customize data directory location

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#68]
Currently, the Windows version of the engine keeps its data in %appdata%\com.codelobster\PsyDoom. That's convenient for sharing the game with other users on the same PC, but being able to set it to a different location would be convenient for other purposes; like keeping the data on a removable device, having it automatically synced to remote storage, or minimizing use of the drive that Windows is installed on.

**Comment by fenderc01** [comment]
You can currently copy your ini files to the same folder as PsyDoom.exe and it will read it from there.

**Comment by SoddenCub71** [comment]
Thanks for the tip; but it doesn't seem to read save files from there.
![image](https://user-images.githubusercontent.com/114965480/197350222-e7204a74-64bb-49c5-9039-11b54c48973b.png)

**Comment by fenderc01** [comment]
No, unfortunately I made that suggestion and it wasn't accepted.

https://github.com/BodbDearg/PsyDoom/issues/42

**Comment by BodbDearg** [comment]
@SoddenCub71 see #42 for my thoughts on this. As a workaround, if you really need to relocate the data folder then symlinks could be used as suggested in #42.
