### ISSUE TITLE
[Bug] Level timer resets

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#69]
The first time a save file is loaded after the game is launched or a level is started, the level timer starts at zero. If the player saves, or completes a level, the timestamp on the Load/Save or intermission screen (as applicable) will only show the time elapsed since the file was loaded.
https://user-images.githubusercontent.com/114965480/198701759-3cc3b9a3-49b5-4ee5-abce-e4750ed2002f.mp4

**Comment by BodbDearg** [comment]
Good catch, thank you for pointing this out.

**Comment by BodbDearg** [comment]
Closing as fixed as of 1.1.0.
