### ISSUE TITLE
Credits Disappear in "Classic Renderer" Mode

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#7]
The credits disappear at the top of the screen in "Classic Renderer" mode, but work fine in "Vulkan Renderer" mode.

**Comment by BodbDearg** [comment]
Thanks for pointing this out @fenderc01 will take a look shortly!

**Comment by BodbDearg** [comment]
Should be fixed now with aa2e2a5bfc13c0729922702ddb14f5bc2da234f4.
