### ISSUE TITLE
[Feature suggestion] Autoaiming indicator

### ISSUE THREAD

**Issue by getphobo** [BodbDearg/PsyDoom#70]
One thing I've always missed in classic Doom that got implemented in PrBoom+ years later is a visual autoaiming indicator that indicates when the game has detected and is autoaiming at a shootable object which is below or above the center of the player's FOV.

It would be very helpful is PsyDoom, too.

**Comment by BodbDearg** [comment]
While I understand the intent of this feature it feels a little too far removed from vanilla PSX Doom and beyond the scope of what PsyDoom is intended to achieve. Besides, there is a lot of randomness with aiming for many weapons and the indicator may be misleading in some cases depending on what directions the bullets are randomly scattered.
