### ISSUE TITLE
[Tweak][Mod] Option for PC Doom frame data

### ISSUE THREAD

**Issue by pas-de-2** [BodbDearg/PsyDoom#71]
It would be nice to able to restore the PC frame data for the various monsters that got nerfed in the transition to console. Restore randomness to Revenant missiles, and speed up the projectiles that got slowed down (Revenant, Arachnotron, Mancubus).

Just an idea for making M+Keyboard play with Psydoom better. I love the atmosphere of PSX Doom but I always feel a bit bad beating up on the nerfed boneman.

**Comment by NightFright2k19** [comment]
I don't think the point of the port should be to get closer to the PC version. If it's just about making it possible to mod the game, I guess it's OK. But it shouldn't be an ingame option or anything.

**Comment by BodbDearg** [comment]
Changing the timebase of the game is actually a huge change, and I feel it would take too much away from the feel of PSX Doom. The goal of PsyDoom is to remain fairly reasonably faithful to the original game, while adding some quality of life enhancements (within reason). Closing ticket - beyond the scope of this project.

**Comment by pas-de-2** [comment]
Oh I never meant that you should change the timebase of the game, which would be asking too much, just patch in the closest possible multiples when taking into account the Hz difference, eg. A_TroopAttack is 6 frames in PC but 3 frames in PSX Doom as a rough equivalent.
