### ISSUE TITLE
[Bug?] Misleading intermission screen

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#72]
When I beat Level 30: Threshold of Pain, the intermission screen says "Entering Entryway"; but it actually returns me to the main menu.

https://user-images.githubusercontent.com/114965480/199884631-b9ef520d-c32d-4bbb-9ef2-1ca3f217d69b.mp4

I don't know whether that's what it originally said and did; or whether it should still be changed if so. I was a bit annoyed to be four levels into Doom II before realizing I could have kept my inventory from Ultimate Doom, though.

**Comment by NightFright2k19** [comment]
I also thought you are supposed to smoothly transit into the Doom 2 campaign, but after asking in the Doomworld forums, that's apparently how it's meant to be. It forces you back into the menu.

**Comment by BodbDearg** [comment]
Yeah it's a bit weird and confusing but this is how the game is supposed to function and not a bug. It's telling you what the next level will be when you use the password displayed, which has already been set in the password menu.
