### ISSUE TITLE
[feature] colored monster blood

### ISSUE THREAD

**Issue by DoodlesYT** [BodbDearg/PsyDoom#73]
a feature that gives monsters their own unique color for the blood sprites when attacking them, like in Crispy Doom, would be really cool.

**Comment by BodbDearg** [comment]
Thanks for the suggestion but I feel this is out of scope for this project. PsyDoom intends to remain to be reasonably close to the original game with some additional quality of life improvements (within reason). Changing art strays too far from the original game I'm afraid.
