### ISSUE TITLE
Cannot seem to bind controller inputs with dualsense controller

### ISSUE THREAD

**Issue by TheOldKingCole** [BodbDearg/PsyDoom#82]
I wanted to set up the controls like original version and I could not bind anything on my Dualsense

**Comment by BodbDearg** [comment]
Can you confirm if your controller is working with any other games? I don't have this particular device on-hand so can't test myself.

**Comment by BodbDearg** [comment]
This is probably a driver issue or something like that if the controller doesn't work at all. Closing out this issue until there is more info on this indicating a problem with PsyDoom itself. I can also try to update SDL for the next release to improve compatibility with more recent controllers.
