### ISSUE TITLE
[Feature request] 32-bit build?

### ISSUE THREAD

**Issue by getphobo** [BodbDearg/PsyDoom#83]
BodbDearg,
Could you make a 32-bit build of PsyDoom, so it could run on 32-bit Windows?

**Comment by BodbDearg** [comment]
I don't officially support 32-bit Windows because it is such a tiny fraction of the userbase and falling. According to the latest Steam Hardware survey (https://store.steampowered.com/hwsurvey) just 0.11% of players are now on Windows 7 32-bit.

I also don't want to cause unnecessary confusion with the 64-bit binary and have users suffer performance or compatibility issues because of mixing them up. 32-bit is completely untested and unsupported for PsyDoom on Windows.

If you're really desperate for a 32-bit Windows binary PsyDoom _can_ be compiled to target 32-bit if you build locally. I can attach a build to this ticket for the next release to save you that trouble, but I won't be adding it to the official releases page for the reasons listed above.

**Comment by getphobo** [comment]
Thanks, if you could make it possible to build it by oneself easily, that would be good enough for me.
I'm not a coder myself but do have some basic experience with successful source code compilations (several Linux kernels and some SDL2 games).

**Comment by Bluethunder83** [comment]
I built a 32bit build of the latest version
[PsyDoom 1.0.1 Win32.zip](https://github.com/BodbDearg/PsyDoom/files/10469006/PsyDoom.1.0.1.Win32.zip)

**Comment by getphobo** [comment]
Oh, sweet! Thanks a lot! It runs very well.

Although, it needs to be noted that those old systems do not support Vulkan, so they run the classic renderer.

**Comment by michaelmouton** [comment]
> I built a 32bit build of the latest version [PsyDoom 1.0.1 Win32.zip](https://github.com/BodbDearg/PsyDoom/files/10469006/PsyDoom.1.0.1.Win32.zip)

Awesome work, but Google refuses to download, saying "virus detected".

**Comment by getphobo** [comment]
Interesting. It doesn't do on my end.

**Comment by michaelmouton** [comment]
https://www.virustotal.com/gui/file/20ecb9378ae5e3a58f95cb99f588400720d5e535713b5faad171e9f4263e7497/detection
https://opentip.kaspersky.com/20ECB9378AE5E3A58F95CB99F588400720D5E535713B5FAAD171E9F4263E7497/results?tab=upload

I guess false positive...?

**Comment by Bluethunder83** [comment]
I'm pretty sure it is, I uploaded it and when and when I download it does the same thing,  Its the antivirus stuff being overprotective.

**Comment by getphobo** [comment]
> I guess false positive...?

Well, without knowing the reason why it was flagged, one could only speculate. Saying "Its the antivirus stuff being overprotective" is in line with common experience... but also incredibly suspicious.
New malware will typically not be discovered by all of the vendors but mostly just one or a handful.

Anyway, I have submitted a false positive report to SecureAge for their review. Let's see what they say.

**Comment by Bluethunder83** [comment]
Not a bad idea, I will say the only time I have ever had a similar problem is downloading binaries on github in general,  not always just randomly,  I always get the message that its not normally downloaded and are you sure.  Plus the fact that its not commercially recognized software it flags it as suspicious.

**Comment by getphobo** [comment]
Good news: SecureAdd have cleared the false detection last night. It still may take a few days to take effect in VirusTotal, though. They wrote:

> Your submission (20230126-032659413500/PsyDoom.exe) has been successfully processed. Your false detection(s) will be cleared within the next 72 hours; please notify us at secureaplus@secureage.com if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyse files in order to get the updated detection result.

So I suggest not to reupload the file for a scan until next Tuesday or so. I'm going to close this issue as I do not see any further problems here.

**Comment by BodbDearg** [comment]
Here's a 32-bit version of 1.1.0:
[PsyDoom_1.1.0_Windows_x86.zip](https://github.com/BodbDearg/PsyDoom/files/10891615/PsyDoom_1.1.0_Windows_x86.zip)
