### ISSUE TITLE
[Feature Request] pk3/zip format support for mods

### ISSUE THREAD

**Issue by DoodlesYT** [BodbDearg/PsyDoom#84]
I feel this should be a feature, as using a more compressed file type can help save up on disk space, especially if you have a lot of mods downloaded.

**Comment by BodbDearg** [comment]
Thanks for the suggestion. Disk space is cheap these days however and mods are relatively tiny in comparison to what we are used to with modern stuff. There's also not a huge amount of PsyDoom mods currently. Doesn't feel like this is worth the effort involved right now - closing.
