### ISSUE TITLE
Portable config/saves location no longer works in newer GUI version. 

### ISSUE THREAD

**Issue by brad86m** [BodbDearg/PsyDoom#85]
I personally prefer having data away from AppData folders, but with newer versions, saves and some settings are located in local/user, again.

Any way to make full portability ?

Thanks :)

**Comment by fenderc01** [comment]
You can sort of make it portable by copying the .ini files to the same folder as the executable. Your save files won't be portable though, but your configuration and passwords will be.

**Comment by brad86m** [comment]
I have done that since early versions and it worked well. Some settings with newer releases will not be portable, though.

**Comment by BodbDearg** [comment]
This is already covered by #42. If you _really_ need to relocate the data folder then the suggestion would be to use symlinks or something of that kind.
