### ISSUE TITLE
[Feature Request] Mod directory "Browse" defaults to current directory

### ISSUE THREAD

**Issue by cf4892** [BodbDearg/PsyDoom#87]
I think it would make more sense if the launcher would default to the same folder that the executable is running from when browsing for a mod directory. I'm assuming most people will keep their mods in a sub-folder of where their PsyDoom executable is located.

Right now (in Windows), when you click browse, it defaults to your user folder (i.e. c:\Users\username). With my proposed change, it would default to %path-to-PsyDoom.exe% (i.e. c:\games\PsyDoom).

**Comment by cf4892** [comment]
I was signed in under the wrong account when I posted this. It should be credited to @fenderc01.

**Comment by BodbDearg** [comment]
Alright 👍

**Comment by BodbDearg** [comment]
Closing as implemented as of 1.1.0.
