### ISSUE TITLE
[Bug] IDKFA cheat won't give all keys

### ISSUE THREAD

**Issue by atalarikt99** [BodbDearg/PsyDoom#89]
While it shows the "Lots of goodies!" message distinct from IDFA's "Lots of goodies! (No Keys)" message, no keys are, in fact, given after typing IDKFA.

**Comment by fenderc01** [comment]
It only gives you the keys that are needed for that map. This is the same behavior as on the PlayStation version.

**Comment by atalarikt99** [comment]
Ah, I see! Although, I just noticed that the requirement is that at least one key has to be put inside the map. Therefore, a colored door that requires a key won't be openable without that key in the map, even with the IDKFA cheat.

**Comment by fenderc01** [comment]
You're right. That's what I meant. It gives you the keys found in the map.

Here's the code, if you're curious:
https://github.com/BodbDearg/PsyDoom/blob/d01e8e0bc171386469ee23f22dc5e9e8d01d7119/game/PsyDoom/Cheats.cpp#L139-L156

**Comment by BodbDearg** [comment]
Yeah the behavior is as @fenderc01 describes and is how it was in the original game. The cheat will only give you whatever keys happen to be present in the map, and if there are no keys lying around then you won't get any of them. Closing as a non-issue (working as expected).
