### ISSUE TITLE
Excessive registry access when window is minimized (due to swap chain creation fail)

### ISSUE THREAD

**Issue by tigrouind** [BodbDearg/PsyDoom#91]
I noticed that the PsyDoom process does a lot of registry accesses once minimized. It quickly reach **hundred thousands** hits after a few seconds. Here is the output of ProcessMonitor : 
![image](https://user-images.githubusercontent.com/2211721/235355656-47869275-d7fe-4165-9853-9a48ce75467a.png)

Looking at the screenshot, it seems to be related to the video card/GPU. 

EDIT : this is triggered by those methods, called every frame : 
```
VRenderer::beginFrame()
VRenderer::ensureValidSwapchainAndFramebuffers()
	Swapchain::init()
		DeviceSurfaceCaps::query()
			vkGetPhysicalDeviceSurfaceFormatsKHR()       // registry access
			vkGetPhysicalDeviceSurfaceFormatsKHR()       //
			vkGetPhysicalDeviceSurfacePresentModesKHR()  //
```

There is an attempt to create a swap chain every frame but it fails :
```
// Swapchain creation can fail validly if the window is zero sized and cannot currently be presented to
if (mDeviceSurfaceCaps.isZeroSizedMaxImageExtent())
	return false;
```

While having the game minimized is not how PsyDoom is supposed to be played, this should not perform so many accesses to the registry.

Some ideas to prevent this : 
- delay swap chain creation after it fails (eg: by one second).
- detect if window is minimized and skip rendering (and thus creation of swap chain).
- pause/sleep the game if window is minimized.

**Comment by BodbDearg** [comment]
The fix for this issue is now available in [1.1.1](https://github.com/BodbDearg/PsyDoom/releases/tag/releases%2F1.1.1), registry access should be greatly reduced now in the minimized state. Closing ticket.
