### ISSUE TITLE
Couldn't get any sound until deleting AppData\Roaming\com.codelobster\PsyDoom

### ISSUE THREAD

**Issue by aybe** [BodbDearg/PsyDoom#92]
The fix is in the title, it seems that somehow, settings of an older version will screw that last release I just downloaded now.

I thought it was because of multi-tracks bin/cue but no, deleting the above and everything is back to normal.

When I mean no sound, not in intro video and no music, sfx were still ok.

Here's a copy of the folder in appdata, in case you want to try diagnose the issue:

[PsyDoom.zip](https://github.com/BodbDearg/PsyDoom/files/11414162/PsyDoom.zip)

**Comment by Bendy-Gaming** [comment]
Maybe it's because you set the music volume to 0.

**Comment by aybe** [comment]
You are absolutely right, there was `musicVol = 0` in some of the settings! 😅
