### ISSUE TITLE
Way to bypass the launcher?

### ISSUE THREAD

**Issue by Tasosgemah** [BodbDearg/PsyDoom#94]
The launcher makes it mandatory that you use a mouse to click, in order to launch the game.

This makes it unusable for couch setups with only a controller.

Is there a way to bypass it and be able to launch it with a game pad, just like the older versions before the launcher?

**Comment by fenderc01** [comment]
According to the README.md...
> To skip showing the launcher on startup specify -nolauncher or any other command line argument.

https://github.com/BodbDearg/PsyDoom/tree/master#Command-line-arguments

**Comment by Tasosgemah** [comment]
Thanks, i completely missed that
