### ISSUE TITLE
Request: Damage multiplier cheat

### ISSUE THREAD

**Issue by daninthemix** [BodbDearg/PsyDoom#95]
This project is amazing. Thankyou!

I have a request for a new cheat that would be quite fun: Damage multipliers, both for enemies and the player, allowing you to precisely tweak the difficulty in both directions.

**Comment by BodbDearg** [comment]
Thanks for the suggestion. I thought about it but came to the conclusion that it might upset the balance of the game a little too much and not end up as fun as it sounds in practice. Therefore it might not be worth the effort to implement. I'm not aware of any other Doom source ports that offer a similar option - probably for very similar reasons.
