### ISSUE TITLE
Convert PC WAD to PSX format

### ISSUE THREAD

**Issue by coldner** [BodbDearg/PsyDoom#99]
I love PsyDoom, but there is one big problem with PSX Doom in general: the lack of compatible maps.
Do you think it is possible to convert WADs from PC format to PSX format?

**Comment by michaelmouton** [comment]
https://www.doomworld.com/forum/topic/101161-gec-master-edition-psx-doom-for-the-playstation-beta-4-released-11162022/

There are tools available to do the job.  Unfortunately it's something that needs to be manually done for the most part.
